### PR TITLE
Bump version (0.5)

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by fredrikekre** [comment]
Should have been 0.4.9?

**Comment by oxinabox** [comment]
True

**Comment by oxinabox** [comment]
Let's yank v5 and tag v4.9

**Comment by oxinabox** [comment]
Let's yank v0.5 and tag v0.4.9.

**Comment by oxinabox** [comment]
Also let's delete deprecations and tag v1.0.0 and avoid confusion in future.

**Comment by quinnj** [comment]
Yeah, 1.0.0 sounds like the right plan.

**Pull request merged**
